### ISSUE TITLE
`remove` command is failing w/ jsonnet

### ISSUE THREAD

**Issue by Quentin-M** [coreos/kpm#105]
```
Traceback (most recent call last):
  File "/usr/local/bin/kpm", line 4, in <module>
    __import__('pkg_resources').run_script('kpm==0.21.0', 'kpm')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/kpm-0.21.0-py2.7.egg/EGG-INFO/scripts/kpm", line 6, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/kpm-0.21.0-py2.7.egg/kpm/command.py", line 18, in cli
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/kpm-0.21.0-py2.7.egg/kpm/commands/command_base.py", line 16, in call
    self(options)()
  File "/usr/local/lib/python2.7/dist-packages/kpm-0.21.0-py2.7.egg/kpm/commands/command_base.py", line 19, in __call__
    self._call()
  File "/usr/local/lib/python2.7/dist-packages/kpm-0.21.0-py2.7.egg/kpm/commands/remove.py", line 25, in _call
    jsonnet=self.isjsonnet,
AttributeError: 'RemoveCmd' object has no attribute 'isjsonnet'
```

**Comment by ant31** [comment]
Fixed
