### ISSUE TITLE
Error during kpm new command

### ISSUE THREAD

**Issue by sheerun** [coreos/kpm#147]
```
python --version
Python 2.7.13
```

```
Api-version: .. Connection error
Client-version: 0.24.1
```

```
kpm new foo/bar
Namespace(directory='.', func=<bound method type.call of <class 'kpm.commands.new.NewCmd'>>, output='text', package=['foo/bar'], with_comments=False)
Traceback (most recent call last):
  File "/usr/local/bin/kpm", line 6, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/kpm/command.py", line 83, in cli
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/kpm/commands/command_base.py", line 27, in call
    cls(options)()
  File "/usr/local/lib/python2.7/site-packages/kpm/commands/command_base.py", line 30, in __call__
    self._call()
  File "/usr/local/lib/python2.7/site-packages/kpm/commands/new.py", line 29, in _call
    self.path = kpm.new.new_package(self.package, self.directory, self.with_comments)
  File "/usr/local/lib/python2.7/site-packages/kpm/new.py", line 77, in new_package
    _, app = name.split("/")
AttributeError: 'list' object has no attribute 'split'
```

The first line comes from a `print(options)` I've added in `commands/new.py`

**Comment by ant31** [comment]
@sheerun thank for report. 
The new command needs to be reworked. Sorry you ran into this. 
Will update shortly
